/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针（不触碰任何依赖） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 服务存活 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["HealthData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针（检查数据库与 agent 可达） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 各依赖的状态；任一为 down 时 HTTP 仍为 200，由调用方判断 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["ReadyData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册博主（同时自动创建租户） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterInput"];
                };
            };
            responses: {
                /** @description 注册成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["AuthResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["AuthResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用 refresh token 换新的 access token（并轮换 refresh token）
         * @description refresh token 从 httpOnly Cookie 读取，不接受请求体传入。
         *
         *     每次刷新都会签发新的 refresh token 并作废旧的。若检测到已作废的 refresh token 被再次使用（重放），判定为凭据泄露并吊销【整个会话族】，返回 1401。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["RefreshResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出当前设备（吊销当前会话族） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["RevokeResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出所有设备
         * @description 改密码或发现异常登录时应调用。已签发的 access token 会在下次请求时被拒。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出全部 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["RevokeResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前账号的活跃会话列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 会话列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["SessionInfo"][];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户与租户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当前身份 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["MeResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的专家列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["Expert"][];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /** 创建 AI 专家 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExpertInput"];
                };
            };
            responses: {
                /** @description 创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["Expert"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 专家详情（含最近一次构建进度）
         * @description 不属于当前租户时返回 404 而非 403 —— 不泄露资源是否存在。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["ExpertDetail"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts/{id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 素材列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["Material"][];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 上传素材（粘贴正文 / 文件 / 链接）
         * @description 链接抓取只承诺公众号，其他平台尽力而为；失败时前端应引导用户改用粘贴正文。内容哈希重复时复用已有素材，返回 deduplicated: true。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMaterialInput"];
                };
            };
            responses: {
                /** @description 上传成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["CreateMaterialResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按分享短链获取专家信息
         * @description 专家未上线时返回 404 —— 不泄露这个短链是否存在过。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 专家信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["ChatExpertInfo"];
                        };
                    };
                };
                /** @description 短链无效或专家未上线 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 向 AI 专家提问（SSE 流式返回）
         * @description 以 text/event-stream 返回，事件协议见 contracts/README.md。
         *
         *     召回结果全部低于置信度阈值时，直接回答「这个他没有讲过」，不调用生成模型 ——既防幻觉，也不为库里没有的问题花钱。
         *
         *     试聊额度用完时发 `event: error` + `code: 402`，而不是断流。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatInput"];
                };
            };
            responses: {
                /** @description SSE 事件流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["ChatStream"];
                    };
                };
                /** @description 短链无效或专家未上线 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts/{id}/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取七维专家模型（AI 草稿 + 博主定稿）
         * @description draft 是 AI 生成的草稿，confirmed 是博主确认过的定稿。
         *
         *     条目的 evidenceChunkIds 为空表示【原文里找不到出处，是 AI 推断的】—— 前端必须标红。这是防过度推断的核心机制，见产品文档 §8.3。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 七维模型 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["ModelView"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts/{id}/model/{dimension}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 确认单个维度（分块确认）
         * @description 一次只提交一个维度，对应产品文档 §8.4 的「分块确认」—— 让博主一次看一块、改一块，而不是面对一个巨大的表单。
         *
         *     提交即视为确认该维度；未提交的维度按草稿「默认通过」。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    dimension: components["schemas"]["Dimension"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmDimensionInput"];
                };
            };
            responses: {
                /** @description 已确认 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["ModelView"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts/{id}/model/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新生成七维草稿（不重新向量化）
         * @description 只跑提炼，直接复用已有的知识切片。博主会反复重新生成直到满意，每次都重跑 embedding 是真金白银。
         *
         *     已确认的维度不受影响 —— 草稿和定稿是分开存的。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已入队 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["BuildResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上线，生成分享链接
         * @description 上线前校验禁区（boundaries）非空 —— 它是合规生命线，必须由博主主动确认，见产品文档 §7.2。
         *
         *     重复上线不会改变已生成的 share_slug。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已上线 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["PublishResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experts/{id}/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 触发构建（解析 → 切分 → 向量化）
         * @description 立即返回 jobId；进度通过 GET /api/experts/{id} 的 lastBuild 轮询。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已入队 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 0 = 成功；非 0 见 contracts/README.md
                             * @example 0
                             */
                            code: number;
                            /** @example ok */
                            message: string;
                            data: components["schemas"]["BuildResult"];
                        };
                    };
                };
                /** @description 未登录或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description 资源不存在，或不属于当前租户（刻意不区分，避免泄露存在性） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthData: {
            /** @example backend */
            service: string;
            /** @enum {string} */
            status: "ok";
        };
        ReadyData: {
            /** @enum {string} */
            database: "ok" | "down";
            /** @enum {string} */
            agent: "ok" | "down";
        };
        UserPublic: {
            /** Format: uuid */
            id: string;
            email: string | null;
            phone: string | null;
            nickname: string | null;
            /** @enum {string} */
            role: "creator" | "user";
        };
        TenantPublic: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        AuthResult: {
            /** @description 放 Authorization: Bearer <token>，15 分钟有效 */
            accessToken: string;
            /**
             * @description access token 剩余秒数
             * @example 900
             */
            expiresIn: number;
            user: components["schemas"]["UserPublic"];
            tenant: components["schemas"]["TenantPublic"];
        };
        ErrorBody: {
            /** @example 1401 */
            code: number;
            /** @example 未登录 */
            message: string;
            data: null;
        };
        RegisterInput: {
            /** Format: email */
            email?: string;
            phone?: string;
            /** @description 至少 8 位 */
            password: string;
            nickname?: string;
        };
        LoginInput: {
            /** @description 邮箱或手机号 */
            account: string;
            password: string;
        };
        RefreshResult: {
            accessToken: string;
            /** @example 900 */
            expiresIn: number;
        };
        RevokeResult: {
            /** @description 被吊销的会话数 */
            revoked: number;
        };
        SessionInfo: {
            /** Format: uuid */
            id: string;
            userAgent: string | null;
            ip: string | null;
            /** @description 是否为当前这次登录 */
            current: boolean;
            /** Format: date-time */
            lastUsedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        MeResult: {
            user: components["schemas"]["UserPublic"];
            tenant: components["schemas"]["TenantPublic"];
        };
        /** @enum {string} */
        ExpertStatus: "building" | "online" | "offline";
        Expert: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["ExpertStatus"];
            materialCount: number;
            chunkCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateExpertInput: {
            name: string;
        };
        /**
         * @description 构建阶段。extracting = 正在提炼七维专家模型。
         * @enum {string|null}
         */
        BuildStage: "queued" | "parsing" | "chunking" | "embedding" | "extracting" | "done" | null;
        BuildProgress: {
            /** Format: uuid */
            jobId: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            progress: number;
            stage: components["schemas"]["BuildStage"];
            /** @description 失败时的可读原因 */
            error: string | null;
            /** Format: date-time */
            updatedAt: string;
        } | null;
        ExpertDetail: components["schemas"]["Expert"] & {
            lastBuild: components["schemas"]["BuildProgress"];
            /** @description 是否已有 AI 生成的七维草稿 */
            hasDraft: boolean;
            /** @description 博主已确认的维度 */
            confirmedDimensions: string[];
            shareSlug: string | null;
            /** Format: date-time */
            publishedAt: string | null;
        };
        /**
         * @description paste=粘贴正文（最可靠）；file=上传文件；url=粘贴链接（只承诺公众号）
         * @enum {string}
         */
        SourceType: "paste" | "file" | "url";
        Material: {
            /** Format: uuid */
            id: string;
            sourceType: components["schemas"]["SourceType"];
            title: string | null;
            sourceUrl: string | null;
            charCount: number;
            /** @description sha256，用于去重 */
            contentHash: string;
            chunkCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateMaterialResult: {
            material: components["schemas"]["Material"];
            /** @description true 表示内容哈希已存在，复用了已有素材而非新建 */
            deduplicated: boolean;
        };
        CreateMaterialInput: {
            /** @enum {string} */
            sourceType: "paste";
            title: string;
            content: string;
        } | {
            /** @enum {string} */
            sourceType: "file";
            title: string;
            filename: string;
            contentBase64: string;
        } | {
            /** @enum {string} */
            sourceType: "url";
            /**
             * Format: uri
             * @example https://mp.weixin.qq.com/s/xxxx
             */
            url: string;
        };
        ChatExpertInfo: {
            name: string;
            creatorNickname: string | null;
            knowledgeSize: number;
            priceCents: number;
            trialRemaining: number;
        };
        /** @description SSE 事件流，协议见 contracts/README.md */
        ChatStream: string;
        ChatInput: {
            question: string;
        };
        ModelItem: {
            content: string;
            confidence: number;
            /** @description 出自哪几个知识切片。为空 = AI 推断，原文无出处，前端标红。 */
            evidenceChunkIds: string[];
        };
        /**
         * @description 冒充风险 / 专业建议风险 / 立场越界 —— 产品文档 §7.2 的三层边界
         * @enum {string}
         */
        BoundaryKind: "impersonation" | "professional_advice" | "out_of_scope";
        BoundaryItem: {
            content: string;
            kind: components["schemas"]["BoundaryKind"];
        };
        ExampleItem: {
            question: string;
            answer: string;
            evidenceChunkIds: string[];
        };
        /** @enum {string} */
        Dimension: "persona" | "knowledge" | "beliefs" | "methodology" | "decisionRules" | "boundaries" | "examples";
        ModelView: {
            draft: {
                persona: components["schemas"]["ModelItem"][];
                knowledge: components["schemas"]["ModelItem"][];
                beliefs: components["schemas"]["ModelItem"][];
                methodology: components["schemas"]["ModelItem"][];
                decisionRules: components["schemas"]["ModelItem"][];
                boundaries: components["schemas"]["BoundaryItem"][];
                examples: components["schemas"]["ExampleItem"][];
            } | null;
            /** Format: date-time */
            generatedAt: string | null;
            confirmed: {
                persona: components["schemas"]["ModelItem"][];
                knowledge: components["schemas"]["ModelItem"][];
                beliefs: components["schemas"]["ModelItem"][];
                methodology: components["schemas"]["ModelItem"][];
                decisionRules: components["schemas"]["ModelItem"][];
                boundaries: components["schemas"]["BoundaryItem"][];
                examples: components["schemas"]["ExampleItem"][];
            } | null;
            /** @description 博主已确认的维度。未确认的维度按草稿「默认通过」。 */
            confirmedDimensions: components["schemas"]["Dimension"][];
            chunkCount: number;
        };
        ConfirmDimensionInput: {
            /** @description 该维度的最终内容。博主可增删改；提交即视为确认这一维度。 */
            items: (components["schemas"]["ModelItem"] | components["schemas"]["BoundaryItem"] | components["schemas"]["ExampleItem"])[];
        };
        BuildResult: {
            /** Format: uuid */
            jobId: string;
        };
        PublishResult: {
            shareSlug: string;
            shareUrl: string;
            /** Format: date-time */
            publishedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
